### ISSUE TITLE
 import io.mezon.rnslider.RNSliderPackage;

### ISSUE THREAD

**Issue by GedoonS** [mezonio/react-native-slider-android#1]
Please add in the instructions step 4:

// MainActivity.java
import io.mezon.rnslider.RNSliderPackage; // <--- add this
...

For a junior RN coder like me it took a while to realize that was supposed to be there, and then finding out what the exact line should be.

**Comment by Daneel-Reventlov** [comment]
Thanks **GedoonS** I have just added the import line. 
I suggest using **android studio**. It is a free IDE that helps you a lot. 
(For example handles imports automatically.)
